name: CI Ambev

on:
  push:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Instalando as dependencias do node
      run: npm install --force
      
    - name: exceutando o cypress
    - run: npx cypress run
